config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end


  def post_params
    params.require(:post).permit(:title, :summary, :body)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDevSimple</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= link_to 'Все статьи', posts_path %> | 
    <%= link_to 'Новая статья', new_post_path %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <div class="form-control">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-control">
    <%= f.label :summary %>
    <%= f.text_area :summary %>
  </div>

  <div class="form-control">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="form-control">
    <%= f.submit 'Сохранить' %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Редактирование статьи</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Статьи</h1>

<% @posts.each do |post| %>
  <h2><%= link_to post.title, post_path(post) %></h2>
<% end %>

app/views/posts/new.html.erb
<h1>Новая статья</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= link_to 'Изменить', edit_post_path(@post) %>
<%= link_to 'Удалить', post_path(@post), method: :delete, data: {confirm: 'Вы уверены?'} %>
<p><%= @post.body %></p>